// <auto-generated />
namespace JobInn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adddatabasejobdescriptionfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddatabasejobdescriptionfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201712101627534_add-database-jobdescriptionfield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
