// <auto-generated />
namespace JobInn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class jobseeker_table_jobtypeid_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobseeker_table_jobtypeid_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201712111406227_jobseeker_table_jobtypeid_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
